apiVersion: v1
kind: Service
metadata:
  name: lsm-cluster
  namespace: lsm-cluster
spec:
  clusterIP: None
  selector:
    app: lsm-cluster
  ports:
    - name: http
      port: 8080
      targetPort: 8080
